#!/usr/bin/env python3
"""
ai_slop_guard/generate_registry.py

Regenerates ai_slop_guard/references/registry.md from ai_slop_guard/data/rules.json.
data/rules.json is the source of truth — never hand-edit registry.md.

Usage:
    python3 -m ai_slop_guard.generate_registry
"""

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
DATA = HERE / "data" / "rules.json"
OUT = HERE / "references" / "registry.md"

VERIFIED_LABEL = {True: "yes", False: "no", "partial": "partial"}
STATUS_BADGE = {
    "stable": "stable",
    "experimental": "experimental",
    "planned": "planned",
    "deprecated": "deprecated",
}


def main() -> int:
    payload = json.loads(DATA.read_text(encoding="utf-8"))
    rules = payload["rules"]

    lines = [
        "# Rule registry",
        "",
        f"Generated from `data/rules.json` (rule set v{payload['rule_set_version']}). "
        "Do not edit this file by hand — edit rules.json and re-run "
        "`python3 -m ai_slop_guard.generate_registry`.",
        "",
        "## Coverage",
        "",
        "| ID | Status | Script-verified |",
        "|---|---|---|",
    ]
    for r in rules:
        lines.append(f"| {r['id']} | {STATUS_BADGE[r['status']]} | {VERIFIED_LABEL[r['script_verified']]} |")

    lines += [
        "",
        "## Rules",
        "",
        "| ID | Name | Category | Stage | Status | Script-verified | Languages | Since |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for r in rules:
        langs = ", ".join(r["languages"]) if r["languages"] else "—"
        lines.append(
            f"| {r['id']} | {r['name']} | {r['category']} | {r['stage']} | "
            f"{STATUS_BADGE[r['status']]} | {VERIFIED_LABEL[r['script_verified']]} | {langs} | {r['since']} |"
        )

    lines.append("")
    lines.append("## Descriptions")
    lines.append("")
    for r in rules:
        lines.append(f"### {r['id']} — {r['name']} ({STATUS_BADGE[r['status']]})")
        lines.append("")
        lines.append(r["description"])
        lines.append("")
        phil = r.get("philosophy")
        if phil:
            lines.append(f"**Why:** {phil['why']}")
            lines.append("")
            lines.append("**Example (flagged):**")
            lines.append("```")
            lines.append(phil["example"])
            lines.append("```")
            lines.append("")
            lines.append("**Counterexample (not flagged):**")
            lines.append("```")
            lines.append(phil["counterexample"])
            lines.append("```")
            lines.append("")
            lines.append(f"**Tradeoffs:** {phil['tradeoffs']}")
            lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT}")  # slop-guard: ignore
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
